import type { NextPage } from "next";
import Head from "next/head";
import TestHookForm from "../components/TestHookForm";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TestHookForm />
    </div>
  );
};

export default Home;
